/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-25 22:24:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>Campeonato Paulista</title>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"p-3 m-0 border-0 bd-example\">\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<br />\r\n");
      out.write("	<br />\r\n");
      out.write("	\r\n");
      out.write("	<h1 align=\"center\">Campeonato Paulista de Futebol 2021</h1>\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<table class=\"table table-striped table-hover\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"col\"></th>\r\n");
      out.write("						<th scope=\"col\">Time</th>\r\n");
      out.write("						<th scope=\"col\">Cidade</th>\r\n");
      out.write("						<th scope=\"col\">Estadio</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">1</th>\r\n");
      out.write("						<td>Botafogo</td>\r\n");
      out.write("						<td>Ribeirão Preto</td>\r\n");
      out.write("						<td>Santa Cruz</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">2</th>\r\n");
      out.write("						<td>Corinthians</td>\r\n");
      out.write("						<td>São Paulo</td>\r\n");
      out.write("						<td>Neo Quimica Arena</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">3</th>\r\n");
      out.write("						<td>Ferroviária</td>\r\n");
      out.write("						<td>Araraquara</td>\r\n");
      out.write("						<td>Fonte Luminosa</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">4</th>\r\n");
      out.write("						<td>Guarani</td>\r\n");
      out.write("						<td>Campinas</td>\r\n");
      out.write("						<td>Brinco de Ouro</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">5</th>\r\n");
      out.write("						<td>Inter de Limeira</td>\r\n");
      out.write("						<td>Limeira</td>\r\n");
      out.write("						<td>Limeirão</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">6</th>\r\n");
      out.write("						<td>Ituano</td>\r\n");
      out.write("						<td>Itu</td>\r\n");
      out.write("						<td>Novelli Júnior</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">7</th>\r\n");
      out.write("						<td>Mirassol</td>\r\n");
      out.write("						<td>Mirassol</td>\r\n");
      out.write("						<td>José Maria de Campos Maia</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">8</th>\r\n");
      out.write("						<td>Novorizontino</td>\r\n");
      out.write("						<td>Novo Horizonte</td>\r\n");
      out.write("						<td>Jorge Ismael de Biasi</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">9</th>\r\n");
      out.write("						<td>Palmeiras</td>\r\n");
      out.write("						<td>São Paulo</td>\r\n");
      out.write("						<td>Allianz Parque</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">10</th>\r\n");
      out.write("						<td>Ponte Preta</td>\r\n");
      out.write("						<td>Campinas</td>\r\n");
      out.write("						<td>Moisés Lucarelli</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">11</th>\r\n");
      out.write("						<td>Red Bull Bragantino</td>\r\n");
      out.write("						<td>Bragança Paulista</td>\r\n");
      out.write("						<td>Nabi Abi Chedid</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">12</th>\r\n");
      out.write("						<td>Santo André</td>\r\n");
      out.write("						<td>Santo André</td>\r\n");
      out.write("						<td>Bruno José Daniel</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">13</th>\r\n");
      out.write("						<td>Santos</td>\r\n");
      out.write("						<td>Santos</td>\r\n");
      out.write("						<td>Vila Belmiro</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">14</th>\r\n");
      out.write("						<td>São Bento</td>\r\n");
      out.write("						<td>Sorocaba</td>\r\n");
      out.write("						<td>Walter Ribeiro</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">15</th>\r\n");
      out.write("						<td>São Caetano</td>\r\n");
      out.write("						<td>São Caetano do Sul</td>\r\n");
      out.write("						<td>Anacletto Campanella</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"row\">16</th>\r\n");
      out.write("						<td>São Paulo</td>\r\n");
      out.write("						<td>São Paulo</td>\r\n");
      out.write("						<td>Morumbi</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- End Example Code -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
